# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 400)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.cells = [[0 for _ in range(10)] for _ in range(10)]
        icon_empty = QtGui.QIcon()
        icon_empty.addPixmap(QtGui.QPixmap("icons/empty.png"),
                                 QtGui.QIcon.Normal,
                                 QtGui.QIcon.Off)
        for x in range(10):
            for y in range(10):
                self.cells[x][y] = QtWidgets.QPushButton(self.centralwidget)
                self.cells[x][y].setGeometry(QtCore.QRect(40+y*30, 40+x*30, 30, 30))
                self.cells[x][y].setText("")
                self.cells[x][y].setObjectName(f"cell_{x}_{y}")
                self.cells[x][y].setIcon(icon_empty)
                self.cells[x][y].setIconSize(QtCore.QSize(29, 29))
        self.l_h_0 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_0.setGeometry(QtCore.QRect(40, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_0.setFont(font)
        self.l_h_0.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_0.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_0.setObjectName("l_h_0")
        self.l_h_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_1.setGeometry(QtCore.QRect(68, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_1.setFont(font)
        self.l_h_1.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_1.setObjectName("l_h_1")
        self.l_h_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_2.setGeometry(QtCore.QRect(96, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_2.setFont(font)
        self.l_h_2.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_2.setObjectName("l_h_2")
        self.l_h_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_3.setGeometry(QtCore.QRect(130, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_3.setFont(font)
        self.l_h_3.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_3.setObjectName("l_h_3")
        self.l_h_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_4.setGeometry(QtCore.QRect(160, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_4.setFont(font)
        self.l_h_4.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_4.setObjectName("l_h_4")
        self.l_h_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_5.setGeometry(QtCore.QRect(190, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_5.setFont(font)
        self.l_h_5.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_5.setObjectName("l_h_5")
        self.l_h_6 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_6.setGeometry(QtCore.QRect(220, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_6.setFont(font)
        self.l_h_6.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_6.setObjectName("l_h_6")
        self.l_h_7 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_7.setGeometry(QtCore.QRect(250, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_7.setFont(font)
        self.l_h_7.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_7.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_7.setObjectName("l_h_7")
        self.l_h_8 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_8.setGeometry(QtCore.QRect(280, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_8.setFont(font)
        self.l_h_8.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_8.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_8.setObjectName("l_h_8")
        self.l_h_9 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_9.setGeometry(QtCore.QRect(310, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_9.setFont(font)
        self.l_h_9.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_9.setObjectName("l_h_9")
        self.l_v_0 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_0.setGeometry(QtCore.QRect(10, 40, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_0.setFont(font)
        self.l_v_0.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_0.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_0.setObjectName("l_v_0")
        self.l_v_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_1.setGeometry(QtCore.QRect(10, 70, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_1.setFont(font)
        self.l_v_1.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_1.setObjectName("l_v_1")
        self.l_v_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_2.setGeometry(QtCore.QRect(10, 100, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_2.setFont(font)
        self.l_v_2.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_2.setObjectName("l_v_2")
        self.l_v_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_3.setGeometry(QtCore.QRect(10, 130, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_3.setFont(font)
        self.l_v_3.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_3.setObjectName("l_v_3")
        self.l_v_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_4.setGeometry(QtCore.QRect(10, 160, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_4.setFont(font)
        self.l_v_4.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_4.setObjectName("l_v_4")
        self.l_v_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_5.setGeometry(QtCore.QRect(10, 190, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_5.setFont(font)
        self.l_v_5.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_5.setObjectName("l_v_5")
        self.l_v_6 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_6.setGeometry(QtCore.QRect(10, 220, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_6.setFont(font)
        self.l_v_6.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_6.setObjectName("l_v_6")
        self.l_v_7 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_7.setGeometry(QtCore.QRect(10, 250, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_7.setFont(font)
        self.l_v_7.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_7.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_7.setObjectName("l_v_7")
        self.l_v_8 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_8.setGeometry(QtCore.QRect(10, 280, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_8.setFont(font)
        self.l_v_8.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_8.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_8.setObjectName("l_v_8")
        self.l_v_9 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_9.setGeometry(QtCore.QRect(10, 310, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_9.setFont(font)
        self.l_v_9.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_9.setObjectName("l_v_9")
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(420, 40, 38, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        self.lineEdit_timeout.setFont(font)
        self.lineEdit_timeout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(360, 40, 61, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_time.setFont(font)
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.label_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_time_2.setGeometry(QtCore.QRect(462, 40, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_time_2.setFont(font)
        self.label_time_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_time_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_2.setObjectName("label_time_2")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(360, 200, 181, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(360, 80, 47, 25))
        self.spinBox_4.setProperty("value", 1)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(360, 110, 47, 25))
        self.spinBox_3.setProperty("value", 2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(360, 140, 47, 25))
        self.spinBox_2.setProperty("value", 3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_1.setGeometry(QtCore.QRect(360, 170, 47, 25))
        self.spinBox_1.setProperty("value", 4)
        self.spinBox_1.setObjectName("spinBox_1")
        self.label_sb_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_4.setGeometry(QtCore.QRect(420, 80, 121, 25))
        self.label_sb_4.setObjectName("label_sb_4")
        self.label_sb_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_3.setGeometry(QtCore.QRect(420, 110, 121, 25))
        self.label_sb_3.setObjectName("label_sb_3")
        self.label_sb_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_2.setGeometry(QtCore.QRect(420, 140, 121, 25))
        self.label_sb_2.setObjectName("label_sb_2")
        self.label_sb_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_5.setGeometry(QtCore.QRect(420, 170, 121, 25))
        self.label_sb_5.setObjectName("label_sb_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощник для морского боя"))
        self.l_h_0.setText(_translate("MainWindow", "A"))
        self.l_h_1.setText(_translate("MainWindow", "Б"))
        self.l_h_2.setText(_translate("MainWindow", "В"))
        self.l_h_3.setText(_translate("MainWindow", "Г"))
        self.l_h_4.setText(_translate("MainWindow", "Д"))
        self.l_h_5.setText(_translate("MainWindow", "Е"))
        self.l_h_6.setText(_translate("MainWindow", "Ж"))
        self.l_h_7.setText(_translate("MainWindow", "З"))
        self.l_h_8.setText(_translate("MainWindow", "И"))
        self.l_h_9.setText(_translate("MainWindow", "К"))
        self.l_v_0.setText(_translate("MainWindow", "1"))
        self.l_v_1.setText(_translate("MainWindow", "2"))
        self.l_v_2.setText(_translate("MainWindow", "3"))
        self.l_v_3.setText(_translate("MainWindow", "4"))
        self.l_v_4.setText(_translate("MainWindow", "5"))
        self.l_v_5.setText(_translate("MainWindow", "6"))
        self.l_v_6.setText(_translate("MainWindow", "7"))
        self.l_v_7.setText(_translate("MainWindow", "8"))
        self.l_v_8.setText(_translate("MainWindow", "9"))
        self.l_v_9.setText(_translate("MainWindow", "10"))
        self.lineEdit_timeout.setText(_translate("MainWindow", "1"))
        self.label_time.setText(_translate("MainWindow", "Время:"))
        self.label_time_2.setText(_translate("MainWindow", "сек."))
        self.button_start.setText(_translate("MainWindow", "Рассчитать"))
        self.label_sb_4.setText(_translate("MainWindow", "4-палубников"))
        self.label_sb_3.setText(_translate("MainWindow", "3-палубников"))
        self.label_sb_2.setText(_translate("MainWindow", "2-палубников"))
        self.label_sb_5.setText(_translate("MainWindow", "1-палубников"))

