# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 457)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.cells = [[0 for _ in range(10)] for _ in range(10)]
        icon_empty = QtGui.QIcon()
        icon_empty.addPixmap(QtGui.QPixmap("icons/empty.png"),
                                 QtGui.QIcon.Normal,
                                 QtGui.QIcon.Off)
        for x in range(10):
            for y in range(10):
                self.cells[x][y] = QtWidgets.QPushButton(self.centralwidget)
                self.cells[x][y].setGeometry(QtCore.QRect(40+y*30, 40+x*30, 30, 30))
                self.cells[x][y].setText("")
                self.cells[x][y].setObjectName(f"cell_{x}_{y}")
                self.cells[x][y].setIcon(icon_empty)
                self.cells[x][y].setIconSize(QtCore.QSize(29, 29))
        # self.cell_0_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_1.setGeometry(QtCore.QRect(70, 40, 30, 30))
        # self.cell_0_1.setText("")
        # self.cell_0_1.setObjectName("cell_0_1")
        # self.cell_0_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_2.setGeometry(QtCore.QRect(100, 40, 30, 30))
        # self.cell_0_2.setText("")
        # self.cell_0_2.setObjectName("cell_0_2")
        # self.cell_0_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_3.setGeometry(QtCore.QRect(130, 40, 30, 30))
        # self.cell_0_3.setText("")
        # self.cell_0_3.setObjectName("cell_0_3")
        # self.cell_0_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_4.setGeometry(QtCore.QRect(160, 40, 30, 30))
        # self.cell_0_4.setText("")
        # self.cell_0_4.setObjectName("cell_0_4")
        # self.cell_0_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_5.setGeometry(QtCore.QRect(190, 40, 30, 30))
        # self.cell_0_5.setText("")
        # self.cell_0_5.setObjectName("cell_0_5")
        # self.cell_0_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_6.setGeometry(QtCore.QRect(220, 40, 30, 30))
        # self.cell_0_6.setText("")
        # self.cell_0_6.setObjectName("cell_0_6")
        # self.cell_0_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_7.setGeometry(QtCore.QRect(250, 40, 30, 30))
        # self.cell_0_7.setText("")
        # self.cell_0_7.setObjectName("cell_0_7")
        # self.cell_0_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_8.setGeometry(QtCore.QRect(280, 40, 30, 30))
        # self.cell_0_8.setText("")
        # self.cell_0_8.setObjectName("cell_0_8")
        # self.cell_0_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_0_9.setGeometry(QtCore.QRect(310, 40, 30, 30))
        # self.cell_0_9.setText("")
        # self.cell_0_9.setObjectName("cell_0_9")
        # self.cell_1_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_0.setGeometry(QtCore.QRect(40, 70, 30, 30))
        # self.cell_1_0.setText("")
        # self.cell_1_0.setObjectName("cell_1_0")
        # self.cell_1_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_1.setGeometry(QtCore.QRect(70, 70, 30, 30))
        # self.cell_1_1.setText("")
        # self.cell_1_1.setObjectName("cell_1_1")
        # self.cell_1_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_2.setGeometry(QtCore.QRect(100, 70, 30, 30))
        # self.cell_1_2.setText("")
        # self.cell_1_2.setObjectName("cell_1_2")
        # self.cell_1_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_3.setGeometry(QtCore.QRect(130, 70, 30, 30))
        # self.cell_1_3.setText("")
        # self.cell_1_3.setObjectName("cell_1_3")
        # self.cell_1_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_4.setGeometry(QtCore.QRect(160, 70, 30, 30))
        # self.cell_1_4.setText("")
        # self.cell_1_4.setObjectName("cell_1_4")
        # self.cell_1_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_5.setGeometry(QtCore.QRect(190, 70, 30, 30))
        # self.cell_1_5.setText("")
        # self.cell_1_5.setObjectName("cell_1_5")
        # self.cell_1_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_6.setGeometry(QtCore.QRect(220, 70, 30, 30))
        # self.cell_1_6.setText("")
        # self.cell_1_6.setObjectName("cell_1_6")
        # self.cell_1_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_7.setGeometry(QtCore.QRect(250, 70, 30, 30))
        # self.cell_1_7.setText("")
        # self.cell_1_7.setObjectName("cell_1_7")
        # self.cell_1_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_8.setGeometry(QtCore.QRect(280, 70, 30, 30))
        # self.cell_1_8.setText("")
        # self.cell_1_8.setObjectName("cell_1_8")
        # self.cell_1_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_1_9.setGeometry(QtCore.QRect(310, 70, 30, 30))
        # self.cell_1_9.setText("")
        # self.cell_1_9.setObjectName("cell_1_9")
        # self.cell_2_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_0.setGeometry(QtCore.QRect(40, 100, 30, 30))
        # self.cell_2_0.setText("")
        # self.cell_2_0.setObjectName("cell_2_0")
        # self.cell_2_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_1.setGeometry(QtCore.QRect(70, 100, 30, 30))
        # self.cell_2_1.setText("")
        # self.cell_2_1.setObjectName("cell_2_1")
        # self.cell_2_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_2.setGeometry(QtCore.QRect(100, 100, 30, 30))
        # self.cell_2_2.setText("")
        # self.cell_2_2.setObjectName("cell_2_2")
        # self.cell_2_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_3.setGeometry(QtCore.QRect(130, 100, 30, 30))
        # self.cell_2_3.setText("")
        # self.cell_2_3.setObjectName("cell_2_3")
        # self.cell_2_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_4.setGeometry(QtCore.QRect(160, 100, 30, 30))
        # self.cell_2_4.setText("")
        # self.cell_2_4.setObjectName("cell_2_4")
        # self.cell_2_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_5.setGeometry(QtCore.QRect(190, 100, 30, 30))
        # self.cell_2_5.setText("")
        # self.cell_2_5.setObjectName("cell_2_5")
        # self.cell_2_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_6.setGeometry(QtCore.QRect(220, 100, 30, 30))
        # self.cell_2_6.setText("")
        # self.cell_2_6.setObjectName("cell_2_6")
        # self.cell_2_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_7.setGeometry(QtCore.QRect(250, 100, 30, 30))
        # self.cell_2_7.setText("")
        # self.cell_2_7.setObjectName("cell_2_7")
        # self.cell_2_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_8.setGeometry(QtCore.QRect(280, 100, 30, 30))
        # self.cell_2_8.setText("")
        # self.cell_2_8.setObjectName("cell_2_8")
        # self.cell_2_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_2_9.setGeometry(QtCore.QRect(310, 100, 30, 30))
        # self.cell_2_9.setText("")
        # self.cell_2_9.setObjectName("cell_2_9")
        # self.cell_3_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_0.setGeometry(QtCore.QRect(40, 130, 30, 30))
        # self.cell_3_0.setText("")
        # self.cell_3_0.setObjectName("cell_3_0")
        # self.cell_3_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_9.setGeometry(QtCore.QRect(310, 130, 30, 30))
        # self.cell_3_9.setText("")
        # self.cell_3_9.setObjectName("cell_3_9")
        # self.cell_3_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_3.setGeometry(QtCore.QRect(130, 130, 30, 30))
        # self.cell_3_3.setText("")
        # self.cell_3_3.setObjectName("cell_3_3")
        # self.cell_3_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_4.setGeometry(QtCore.QRect(160, 130, 30, 30))
        # self.cell_3_4.setText("")
        # self.cell_3_4.setObjectName("cell_3_4")
        # self.cell_3_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_8.setGeometry(QtCore.QRect(280, 130, 30, 30))
        # self.cell_3_8.setText("")
        # self.cell_3_8.setObjectName("cell_3_8")
        # self.cell_3_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_2.setGeometry(QtCore.QRect(100, 130, 30, 30))
        # self.cell_3_2.setText("")
        # self.cell_3_2.setObjectName("cell_3_2")
        # self.cell_3_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_1.setGeometry(QtCore.QRect(70, 130, 30, 30))
        # self.cell_3_1.setText("")
        # self.cell_3_1.setObjectName("cell_3_1")
        # self.cell_3_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_6.setGeometry(QtCore.QRect(220, 130, 30, 30))
        # self.cell_3_6.setText("")
        # self.cell_3_6.setObjectName("cell_3_6")
        # self.cell_3_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_5.setGeometry(QtCore.QRect(190, 130, 30, 30))
        # self.cell_3_5.setText("")
        # self.cell_3_5.setObjectName("cell_3_5")
        # self.cell_3_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_3_7.setGeometry(QtCore.QRect(250, 130, 30, 30))
        # self.cell_3_7.setText("")
        # self.cell_3_7.setObjectName("cell_3_7")
        # self.cell_4_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_0.setGeometry(QtCore.QRect(40, 160, 30, 30))
        # self.cell_4_0.setText("")
        # self.cell_4_0.setObjectName("cell_4_0")
        # self.cell_4_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_1.setGeometry(QtCore.QRect(70, 160, 30, 30))
        # self.cell_4_1.setText("")
        # self.cell_4_1.setObjectName("cell_4_1")
        # self.cell_4_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_2.setGeometry(QtCore.QRect(100, 160, 30, 30))
        # self.cell_4_2.setText("")
        # self.cell_4_2.setObjectName("cell_4_2")
        # self.cell_4_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_3.setGeometry(QtCore.QRect(130, 160, 30, 30))
        # self.cell_4_3.setText("")
        # self.cell_4_3.setObjectName("cell_4_3")
        # self.cell_4_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_4.setGeometry(QtCore.QRect(160, 160, 30, 30))
        # self.cell_4_4.setText("")
        # self.cell_4_4.setObjectName("cell_4_4")
        # self.cell_4_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_5.setGeometry(QtCore.QRect(190, 160, 30, 30))
        # self.cell_4_5.setText("")
        # self.cell_4_5.setObjectName("cell_4_5")
        # self.cell_4_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_6.setGeometry(QtCore.QRect(220, 160, 30, 30))
        # self.cell_4_6.setText("")
        # self.cell_4_6.setObjectName("cell_4_6")
        # self.cell_4_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_7.setGeometry(QtCore.QRect(250, 160, 30, 30))
        # self.cell_4_7.setText("")
        # self.cell_4_7.setObjectName("cell_4_7")
        # self.cell_4_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_8.setGeometry(QtCore.QRect(280, 160, 30, 30))
        # self.cell_4_8.setText("")
        # self.cell_4_8.setObjectName("cell_4_8")
        # self.cell_4_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_4_9.setGeometry(QtCore.QRect(310, 160, 30, 30))
        # self.cell_4_9.setText("")
        # self.cell_4_9.setObjectName("cell_4_9")
        # self.cell_5_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_0.setGeometry(QtCore.QRect(40, 190, 30, 30))
        # self.cell_5_0.setText("")
        # self.cell_5_0.setObjectName("cell_5_0")
        # self.cell_5_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_1.setGeometry(QtCore.QRect(70, 190, 30, 30))
        # self.cell_5_1.setText("")
        # self.cell_5_1.setObjectName("cell_5_1")
        # self.cell_5_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_2.setGeometry(QtCore.QRect(100, 190, 30, 30))
        # self.cell_5_2.setText("")
        # self.cell_5_2.setObjectName("cell_5_2")
        # self.cell_5_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_3.setGeometry(QtCore.QRect(130, 190, 30, 30))
        # self.cell_5_3.setText("")
        # self.cell_5_3.setObjectName("cell_5_3")
        # self.cell_5_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_4.setGeometry(QtCore.QRect(160, 190, 30, 30))
        # self.cell_5_4.setText("")
        # self.cell_5_4.setObjectName("cell_5_4")
        # self.cell_5_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_5.setGeometry(QtCore.QRect(190, 190, 30, 30))
        # self.cell_5_5.setText("")
        # self.cell_5_5.setObjectName("cell_5_5")
        # self.cell_5_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_6.setGeometry(QtCore.QRect(220, 190, 30, 30))
        # self.cell_5_6.setText("")
        # self.cell_5_6.setObjectName("cell_5_6")
        # self.cell_5_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_7.setGeometry(QtCore.QRect(250, 190, 30, 30))
        # self.cell_5_7.setText("")
        # self.cell_5_7.setObjectName("cell_5_7")
        # self.cell_5_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_8.setGeometry(QtCore.QRect(280, 190, 30, 30))
        # self.cell_5_8.setText("")
        # self.cell_5_8.setObjectName("cell_5_8")
        # self.cell_5_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_5_9.setGeometry(QtCore.QRect(310, 190, 30, 30))
        # self.cell_5_9.setText("")
        # self.cell_5_9.setObjectName("cell_5_9")
        # self.cell_6_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_0.setGeometry(QtCore.QRect(40, 220, 30, 30))
        # self.cell_6_0.setText("")
        # self.cell_6_0.setObjectName("cell_6_0")
        # self.cell_6_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_1.setGeometry(QtCore.QRect(70, 220, 30, 30))
        # self.cell_6_1.setText("")
        # self.cell_6_1.setObjectName("cell_6_1")
        # self.cell_6_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_2.setGeometry(QtCore.QRect(100, 220, 30, 30))
        # self.cell_6_2.setText("")
        # self.cell_6_2.setObjectName("cell_6_2")
        # self.cell_6_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_3.setGeometry(QtCore.QRect(130, 220, 30, 30))
        # self.cell_6_3.setText("")
        # self.cell_6_3.setObjectName("cell_6_3")
        # self.cell_6_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_4.setGeometry(QtCore.QRect(160, 220, 30, 30))
        # self.cell_6_4.setText("")
        # self.cell_6_4.setObjectName("cell_6_4")
        # self.cell_6_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_6.setGeometry(QtCore.QRect(220, 220, 30, 30))
        # self.cell_6_6.setText("")
        # self.cell_6_6.setObjectName("cell_6_6")
        # self.cell_6_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_5.setGeometry(QtCore.QRect(190, 220, 30, 30))
        # self.cell_6_5.setText("")
        # self.cell_6_5.setObjectName("cell_6_5")
        # self.cell_6_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_7.setGeometry(QtCore.QRect(250, 220, 30, 30))
        # self.cell_6_7.setText("")
        # self.cell_6_7.setObjectName("cell_6_7")
        # self.cell_6_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_8.setGeometry(QtCore.QRect(280, 220, 30, 30))
        # self.cell_6_8.setText("")
        # self.cell_6_8.setObjectName("cell_6_8")
        # self.cell_6_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_6_9.setGeometry(QtCore.QRect(310, 220, 30, 30))
        # self.cell_6_9.setText("")
        # self.cell_6_9.setObjectName("cell_6_9")
        # self.cell_7_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_0.setGeometry(QtCore.QRect(40, 250, 30, 30))
        # self.cell_7_0.setText("")
        # self.cell_7_0.setObjectName("cell_7_0")
        # self.cell_7_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_1.setGeometry(QtCore.QRect(70, 250, 30, 30))
        # self.cell_7_1.setText("")
        # self.cell_7_1.setObjectName("cell_7_1")
        # self.cell_7_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_2.setGeometry(QtCore.QRect(100, 250, 30, 30))
        # self.cell_7_2.setText("")
        # self.cell_7_2.setObjectName("cell_7_2")
        # self.cell_7_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_3.setGeometry(QtCore.QRect(130, 250, 30, 30))
        # self.cell_7_3.setText("")
        # self.cell_7_3.setObjectName("cell_7_3")
        # self.cell_7_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_4.setGeometry(QtCore.QRect(160, 250, 30, 30))
        # self.cell_7_4.setText("")
        # self.cell_7_4.setObjectName("cell_7_4")
        # self.cell_7_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_5.setGeometry(QtCore.QRect(190, 250, 30, 30))
        # self.cell_7_5.setText("")
        # self.cell_7_5.setObjectName("cell_7_5")
        # self.cell_7_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_6.setGeometry(QtCore.QRect(220, 250, 30, 30))
        # self.cell_7_6.setText("")
        # self.cell_7_6.setObjectName("cell_7_6")
        # self.cell_7_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_7.setGeometry(QtCore.QRect(250, 250, 30, 30))
        # self.cell_7_7.setText("")
        # self.cell_7_7.setObjectName("cell_7_7")
        # self.cell_7_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_8.setGeometry(QtCore.QRect(280, 250, 30, 30))
        # self.cell_7_8.setText("")
        # self.cell_7_8.setObjectName("cell_7_8")
        # self.cell_7_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_7_9.setGeometry(QtCore.QRect(310, 250, 30, 30))
        # self.cell_7_9.setText("")
        # self.cell_7_9.setObjectName("cell_7_9")
        # self.cell_8_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_0.setGeometry(QtCore.QRect(40, 280, 30, 30))
        # self.cell_8_0.setText("")
        # self.cell_8_0.setObjectName("cell_8_0")
        # self.cell_8_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_1.setGeometry(QtCore.QRect(70, 280, 30, 30))
        # self.cell_8_1.setText("")
        # self.cell_8_1.setObjectName("cell_8_1")
        # self.cell_8_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_2.setGeometry(QtCore.QRect(100, 280, 30, 30))
        # self.cell_8_2.setText("")
        # self.cell_8_2.setObjectName("cell_8_2")
        # self.cell_8_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_3.setGeometry(QtCore.QRect(130, 280, 30, 30))
        # self.cell_8_3.setText("")
        # self.cell_8_3.setObjectName("cell_8_3")
        # self.cell_8_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_4.setGeometry(QtCore.QRect(160, 280, 30, 30))
        # self.cell_8_4.setText("")
        # self.cell_8_4.setObjectName("cell_8_4")
        # self.cell_8_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_5.setGeometry(QtCore.QRect(190, 280, 30, 30))
        # self.cell_8_5.setText("")
        # self.cell_8_5.setObjectName("cell_8_5")
        # self.cell_8_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_6.setGeometry(QtCore.QRect(220, 280, 30, 30))
        # self.cell_8_6.setText("")
        # self.cell_8_6.setObjectName("cell_8_6")
        # self.cell_8_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_7.setGeometry(QtCore.QRect(250, 280, 30, 30))
        # self.cell_8_7.setText("")
        # self.cell_8_7.setObjectName("cell_8_7")
        # self.cell_8_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_8.setGeometry(QtCore.QRect(280, 280, 30, 30))
        # self.cell_8_8.setText("")
        # self.cell_8_8.setObjectName("cell_8_8")
        # self.cell_8_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_8_9.setGeometry(QtCore.QRect(310, 280, 30, 30))
        # self.cell_8_9.setText("")
        # self.cell_8_9.setObjectName("cell_8_9")
        # self.cell_9_0 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_0.setGeometry(QtCore.QRect(40, 310, 30, 30))
        # self.cell_9_0.setText("")
        # self.cell_9_0.setObjectName("cell_9_0")
        # self.cell_9_1 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_1.setGeometry(QtCore.QRect(70, 310, 30, 30))
        # self.cell_9_1.setText("")
        # self.cell_9_1.setObjectName("cell_9_1")
        # self.cell_9_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_2.setGeometry(QtCore.QRect(100, 310, 30, 30))
        # self.cell_9_2.setText("")
        # self.cell_9_2.setObjectName("cell_9_2")
        # self.cell_9_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_3.setGeometry(QtCore.QRect(130, 310, 30, 30))
        # self.cell_9_3.setText("")
        # self.cell_9_3.setObjectName("cell_9_3")
        # self.cell_9_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_4.setGeometry(QtCore.QRect(160, 310, 30, 30))
        # self.cell_9_4.setText("")
        # self.cell_9_4.setObjectName("cell_9_4")
        # self.cell_9_5 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_5.setGeometry(QtCore.QRect(190, 310, 30, 30))
        # self.cell_9_5.setText("")
        # self.cell_9_5.setObjectName("cell_9_5")
        # self.cell_9_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_6.setGeometry(QtCore.QRect(220, 310, 30, 30))
        # self.cell_9_6.setText("")
        # self.cell_9_6.setObjectName("cell_9_6")
        # self.cell_9_7 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_7.setGeometry(QtCore.QRect(250, 310, 30, 30))
        # self.cell_9_7.setText("")
        # self.cell_9_7.setObjectName("cell_9_7")
        # self.cell_9_8 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_8.setGeometry(QtCore.QRect(280, 310, 30, 30))
        # self.cell_9_8.setText("")
        # self.cell_9_8.setObjectName("cell_9_8")
        # self.cell_9_9 = QtWidgets.QPushButton(self.centralwidget)
        # self.cell_9_9.setGeometry(QtCore.QRect(310, 310, 30, 30))
        # self.cell_9_9.setText("")
        # self.cell_9_9.setObjectName("cell_9_9")
        self.l_h_0 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_0.setGeometry(QtCore.QRect(40, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_0.setFont(font)
        self.l_h_0.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_0.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_0.setObjectName("l_h_0")
        self.l_h_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_1.setGeometry(QtCore.QRect(68, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_1.setFont(font)
        self.l_h_1.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_1.setObjectName("l_h_1")
        self.l_h_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_2.setGeometry(QtCore.QRect(96, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_2.setFont(font)
        self.l_h_2.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_2.setObjectName("l_h_2")
        self.l_h_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_3.setGeometry(QtCore.QRect(130, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_3.setFont(font)
        self.l_h_3.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_3.setObjectName("l_h_3")
        self.l_h_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_4.setGeometry(QtCore.QRect(160, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_4.setFont(font)
        self.l_h_4.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_4.setObjectName("l_h_4")
        self.l_h_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_5.setGeometry(QtCore.QRect(190, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_5.setFont(font)
        self.l_h_5.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_5.setObjectName("l_h_5")
        self.l_h_6 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_6.setGeometry(QtCore.QRect(220, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_6.setFont(font)
        self.l_h_6.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_6.setObjectName("l_h_6")
        self.l_h_7 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_7.setGeometry(QtCore.QRect(250, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_7.setFont(font)
        self.l_h_7.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_7.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_7.setObjectName("l_h_7")
        self.l_h_8 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_8.setGeometry(QtCore.QRect(280, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_8.setFont(font)
        self.l_h_8.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_8.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_8.setObjectName("l_h_8")
        self.l_h_9 = QtWidgets.QLabel(self.centralwidget)
        self.l_h_9.setGeometry(QtCore.QRect(310, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_h_9.setFont(font)
        self.l_h_9.setTextFormat(QtCore.Qt.AutoText)
        self.l_h_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h_9.setObjectName("l_h_9")
        self.l_v_0 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_0.setGeometry(QtCore.QRect(10, 40, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_0.setFont(font)
        self.l_v_0.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_0.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_0.setObjectName("l_v_0")
        self.l_v_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_1.setGeometry(QtCore.QRect(10, 70, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_1.setFont(font)
        self.l_v_1.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_1.setObjectName("l_v_1")
        self.l_v_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_2.setGeometry(QtCore.QRect(10, 100, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_2.setFont(font)
        self.l_v_2.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_2.setObjectName("l_v_2")
        self.l_v_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_3.setGeometry(QtCore.QRect(10, 130, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_3.setFont(font)
        self.l_v_3.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_3.setObjectName("l_v_3")
        self.l_v_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_4.setGeometry(QtCore.QRect(10, 160, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_4.setFont(font)
        self.l_v_4.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_4.setObjectName("l_v_4")
        self.l_v_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_5.setGeometry(QtCore.QRect(10, 190, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_5.setFont(font)
        self.l_v_5.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_5.setObjectName("l_v_5")
        self.l_v_6 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_6.setGeometry(QtCore.QRect(10, 220, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_6.setFont(font)
        self.l_v_6.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_6.setObjectName("l_v_6")
        self.l_v_7 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_7.setGeometry(QtCore.QRect(10, 250, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_7.setFont(font)
        self.l_v_7.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_7.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_7.setObjectName("l_v_7")
        self.l_v_8 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_8.setGeometry(QtCore.QRect(10, 280, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_8.setFont(font)
        self.l_v_8.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_8.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_8.setObjectName("l_v_8")
        self.l_v_9 = QtWidgets.QLabel(self.centralwidget)
        self.l_v_9.setGeometry(QtCore.QRect(10, 310, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_v_9.setFont(font)
        self.l_v_9.setTextFormat(QtCore.Qt.AutoText)
        self.l_v_9.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v_9.setObjectName("l_v_9")
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(420, 40, 38, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        self.lineEdit_timeout.setFont(font)
        self.lineEdit_timeout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(360, 40, 61, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_time.setFont(font)
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.label_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_time_2.setGeometry(QtCore.QRect(462, 40, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_time_2.setFont(font)
        self.label_time_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_time_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_2.setObjectName("label_time_2")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(360, 200, 181, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(360, 80, 47, 25))
        self.spinBox_4.setProperty("value", 1)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(360, 110, 47, 25))
        self.spinBox_3.setProperty("value", 2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(360, 140, 47, 25))
        self.spinBox_2.setProperty("value", 3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_1.setGeometry(QtCore.QRect(360, 170, 47, 25))
        self.spinBox_1.setProperty("value", 4)
        self.spinBox_1.setObjectName("spinBox_1")
        self.label_sb_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_4.setGeometry(QtCore.QRect(420, 80, 121, 25))
        self.label_sb_4.setObjectName("label_sb_4")
        self.label_sb_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_3.setGeometry(QtCore.QRect(420, 110, 121, 25))
        self.label_sb_3.setObjectName("label_sb_3")
        self.label_sb_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_2.setGeometry(QtCore.QRect(420, 140, 121, 25))
        self.label_sb_2.setObjectName("label_sb_2")
        self.label_sb_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_sb_5.setGeometry(QtCore.QRect(420, 170, 121, 25))
        self.label_sb_5.setObjectName("label_sb_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощник для морского боя"))
        self.l_h_0.setText(_translate("MainWindow", "A"))
        self.l_h_1.setText(_translate("MainWindow", "Б"))
        self.l_h_2.setText(_translate("MainWindow", "В"))
        self.l_h_3.setText(_translate("MainWindow", "Г"))
        self.l_h_4.setText(_translate("MainWindow", "Д"))
        self.l_h_5.setText(_translate("MainWindow", "Е"))
        self.l_h_6.setText(_translate("MainWindow", "Ж"))
        self.l_h_7.setText(_translate("MainWindow", "З"))
        self.l_h_8.setText(_translate("MainWindow", "И"))
        self.l_h_9.setText(_translate("MainWindow", "К"))
        self.l_v_0.setText(_translate("MainWindow", "1"))
        self.l_v_1.setText(_translate("MainWindow", "2"))
        self.l_v_2.setText(_translate("MainWindow", "3"))
        self.l_v_3.setText(_translate("MainWindow", "4"))
        self.l_v_4.setText(_translate("MainWindow", "5"))
        self.l_v_5.setText(_translate("MainWindow", "6"))
        self.l_v_6.setText(_translate("MainWindow", "7"))
        self.l_v_7.setText(_translate("MainWindow", "8"))
        self.l_v_8.setText(_translate("MainWindow", "9"))
        self.l_v_9.setText(_translate("MainWindow", "10"))
        self.lineEdit_timeout.setText(_translate("MainWindow", "1"))
        self.label_time.setText(_translate("MainWindow", "Время:"))
        self.label_time_2.setText(_translate("MainWindow", "сек."))
        self.button_start.setText(_translate("MainWindow", "Рассчитать"))
        self.label_sb_4.setText(_translate("MainWindow", "4-палубников"))
        self.label_sb_3.setText(_translate("MainWindow", "3-палубников"))
        self.label_sb_2.setText(_translate("MainWindow", "2-палубников"))
        self.label_sb_5.setText(_translate("MainWindow", "1-палубников"))

